export const PROJECT_ADD_REQUEST = "PROJECT_ADD_REQUEST";
export const PROJECT_ADD_SUCCESS = "PROJECT_ADD_SUCCESS";
export const PROJECT_ADD_FAIL = "PROJECT_ADD_FAIL";
export const PROJECT_ADD_RESET = "PROJECT_ADD_RESET";

export const LIKED_PROJECT_REQUEST = "LIKED_PROJECT_REQUEST";
export const LIKED_PROJECT_SUCCESS = "LIKED_PROJECT_SUCCESS";
export const LIKED_PROJECT_FAIL = "LIKED_PROJECT_FAIL";

export const VIEWED_PROJECT_REQUEST = "VIEWED_PROJECT_REQUEST";
export const VIEWED_PROJECT_SUCCESS = "VIEWED_PROJECT_SUCCESS";
export const VIEWED_PROJECT_FAIL = "VIEWED_PROJECT_FAIL";

export const SEARCH_PROJECT_REQUEST = "SEARCH_PROJECT_REQUEST";
export const SEARCH_PROJECT_SUCCESS = "SEARCH_PROJECT_SUCCESS";
export const SEARCH_PROJECT_FAIL = "SEARCH_PROJECT_FAIL";
