export const PROJECT_ADD_REQUEST = "PROJECT_ADD_REQUEST";
export const PROJECT_ADD_SUCCESS = "PROJECT_ADD_SUCCESS";
export const PROJECT_ADD_FAIL = "PROJECT_ADD_FAIL";
export const PROJECT_ADD_RESET = "PROJECT_ADD_RESET";
